import { notFound } from 'next/navigation';
import { getProject } from '@/domain/project';
import { listCharacters } from '@/domain/character';
import { CharacterForm, CharacterStatusActions } from '@/components/StoryBibleForms';
import Link from 'next/link';
import { StoryBibleHeader, StoryBibleEmpty } from '@/components/StoryBibleLayout';

export const dynamic = 'force-dynamic';
export default async function CharactersPage({ params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const project = await getProject(projectId); if (!project) notFound(); const characters = await listCharacters(projectId); return <main className="mx-auto max-w-5xl px-5 py-10 lg:px-8 lg:py-14"><StoryBibleHeader projectId={projectId} title="Characters" eyebrow="Story bible / roster" copy="Keep identity, voice, and locked traits visible in one place." active="characters" /><div className="grid gap-10 lg:grid-cols-[1fr_300px]"><section><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Roster</h2><span className="mono text-[10px] uppercase tracking-[.16em] text-[#707776]">{characters.length} characters</span></div>{characters.length === 0 ? <StoryBibleEmpty text="No characters yet. Add the first member of the roster." /> : <div className="grid gap-3 sm:grid-cols-2">{characters.map((character) => <article key={character.id} className={`border p-5 ${character.status === 'removed' ? 'border-[#49312e] opacity-70' : 'border-[#2b3030] bg-[#151918]'}`}><div className="flex items-start justify-between gap-3"><div><Link href={`/projects/${projectId}/characters/${character.id}`} className="text-lg font-semibold hover:text-[#c5e86c]">{character.name}</Link><p className="mt-1 text-xs text-[#969b9a]">{character.role}</p></div><span className="mono text-[10px] uppercase tracking-[.14em] text-[#c5e86c]">{character.status}</span></div><p className="mt-5 line-clamp-3 text-sm leading-6 text-[#969b9a]">{character.visualDescription}</p><div className="mt-5 border-t border-[#2b3030] pt-4"><CharacterStatusActions projectId={projectId} character={character} /></div></article>)}</div>}</section><aside className="h-fit border border-[#2b3030] bg-[#151918] p-5"><p className="mono mb-5 text-[10px] uppercase tracking-[.16em] text-[#c5e86c]">Add a character</p><CharacterForm projectId={projectId} /></aside></div></main>; }
