'use client';

import { useActionState, useState } from 'react';
import type { StoryObject } from '@/domain/object';
import type { Character } from '@/domain/character';
import type { Location } from '@/domain/location';
import type { CharacterState, ObjectState } from '@/domain/state';
import {
  createObjectAction, updateObjectAction, deleteObjectAction,
  setCharacterStateAction, clearCharacterStateAction,
  setObjectStateAction, clearObjectStateAction,
  type CurrentStateForm, type CurrentStateMutation,
} from '@/app/actions/currentState';

const inputClass = (error = false) => `w-full border bg-[#151918] px-3 py-3 text-sm text-[#e8e8e3] outline-none placeholder:text-[#606765] focus:border-[#c5e86c] ${error ? 'border-[#f09a8b]' : 'border-[#2b3030]'}`;
const ErrorText = ({ text }: { text?: string }) => text ? <p className="mt-2 text-xs text-[#f09a8b]">{text}</p> : null;
const Message = ({ state }: { state: CurrentStateForm }) => state.message ? <p role="alert" className="border border-[#805047] bg-[#2b1b19] px-4 py-3 text-sm leading-6 text-[#f09a8b]">{state.message}</p> : null;

function Field({ label, name, value, error, area = false, optional = false, disabled = false, placeholder }: { label: string; name: string; value: string; error?: string; area?: boolean; optional?: boolean; disabled?: boolean; placeholder?: string }) {
  return <div><label htmlFor={name} className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">{label} {!optional && <span className="text-[#c5e86c]">*</span>}</label>{area ? <textarea id={name} name={name} defaultValue={value} required={!optional} disabled={disabled} rows={4} placeholder={placeholder} className={inputClass(Boolean(error))} /> : <input id={name} name={name} defaultValue={value} required={!optional} disabled={disabled} placeholder={placeholder} className={inputClass(Boolean(error))} />}<ErrorText text={error} /></div>;
}
function Submit({ pending, label }: { pending: boolean; label: string }) { return <button disabled={pending} className="bg-[#c5e86c] px-5 py-3 text-sm font-bold text-[#0d1110] hover:bg-[#d8f48e] disabled:opacity-60">{pending ? 'Saving…' : label}</button>; }
type MutationAction = (previous: CurrentStateMutation, data: FormData) => Promise<CurrentStateMutation>;
function MutationForm({ action, label }: { action: MutationAction; label: string }) { const [state, formAction, pending] = useActionState(action, {}); return <form action={formAction}><button disabled={pending} className="text-xs text-[#f09a8b] hover:text-white disabled:opacity-50">{pending ? 'Working…' : label}</button>{state.error && <p role="alert" className="mt-2 max-w-xs text-xs leading-5 text-[#f09a8b]">{state.error}</p>}</form>; }

const objectValues = (object?: StoryObject) => ({ name: object?.name ?? '', description: object?.description ?? '', visualLock: object?.visualLock ?? '' });
export function ObjectForm({ projectId, object }: { projectId: string; object?: StoryObject }) { const initial: CurrentStateForm = { errors: {}, values: objectValues(object) }; const actionFn = object ? updateObjectAction.bind(null, projectId, object.id) : createObjectAction.bind(null, projectId); const [state, action, pending] = useActionState(actionFn, initial); const value = (key: string) => state.values[key] ?? ''; return <form action={action} className="space-y-5"><Message state={state} /><Field label="Object name" name="name" value={value('name')} error={state.errors.name} placeholder="e.g. Red key" /><Field label="Description" name="description" value={value('description')} error={state.errors.description} area placeholder="What makes this object identifiable?" /><Field label="Visual lock" name="visualLock" value={value('visualLock')} error={state.errors.visualLock} area optional placeholder="Optional visual reference" /><div className="flex justify-end"><Submit pending={pending} label={object ? 'Save object' : 'Add object'} /></div></form>; }
export function ObjectDelete({ projectId, objectId }: { projectId: string; objectId: string }) { return <MutationForm action={deleteObjectAction.bind(null, projectId, objectId)} label="Delete object" />; }
export function ObjectStateClear({ projectId, objectId }: { projectId: string; objectId: string }) { return <MutationForm action={clearObjectStateAction.bind(null, projectId, objectId)} label="Clear current state" />; }

function stateValue(state: CharacterState | undefined, key: 'locationId' | 'emotion' | 'condition') { return state?.[key] ?? ''; }
export function CharacterStateForm({ projectId, character, state, locations }: { projectId: string; character: Character; state?: CharacterState; locations: Location[] }) { const initial: CurrentStateForm = { errors: {}, values: { locationId: stateValue(state, 'locationId'), emotion: stateValue(state, 'emotion'), condition: stateValue(state, 'condition') } }; const [formState, action, pending] = useActionState(setCharacterStateAction.bind(null, projectId, character.id), initial); const value = (key: string) => formState.values[key] ?? ''; const disabled = character.status === 'removed'; return <div className="space-y-4">{disabled && <p role="alert" className="border border-[#805047] bg-[#2b1b19] px-3 py-2 text-xs leading-5 text-[#f09a8b]">Removed characters keep their existing state, but the domain blocks state edits.</p>}<form action={action} className="space-y-4"><div><label htmlFor={`location-${character.id}`} className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">Location</label><select id={`location-${character.id}`} name="locationId" defaultValue={value('locationId')} disabled={disabled} className={inputClass(Boolean(formState.errors.locationId))}><option value="">Unknown / not initialized</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select><ErrorText text={formState.errors.locationId} /></div><Field label="Emotion" name="emotion" value={value('emotion')} error={formState.errors.emotion} optional disabled={disabled} placeholder="Leave blank if unknown" /><Field label="Condition" name="condition" value={value('condition')} error={formState.errors.condition} optional disabled={disabled} placeholder="Leave blank if unknown" /><div className="flex justify-end"><button disabled={pending || disabled} className="border border-[#c5e86c] px-4 py-2 text-xs font-semibold text-[#c5e86c] hover:bg-[#c5e86c] hover:text-[#0d1110] disabled:opacity-50">{pending ? 'Saving…' : 'Save state'}</button></div></form>{state && !disabled && <MutationForm action={clearCharacterStateAction.bind(null, projectId, character.id)} label="Clear character state" />}</div>; }

export function ObjectStateForm({ projectId, object, state, characters, locations }: { projectId: string; object: StoryObject; state?: ObjectState; characters: Character[]; locations: Location[] }) { const initial: CurrentStateForm = { errors: {}, values: { holderCharacterId: state?.holderCharacterId ?? '', locationId: state?.locationId ?? '', condition: state?.condition ?? '' } }; const [formState, action, pending] = useActionState(setObjectStateAction.bind(null, projectId, object.id), initial); const value = (key: string) => formState.values[key] ?? ''; const [holder, setHolder] = useState(value('holderCharacterId')); const [location, setLocation] = useState(value('locationId')); const available = characters.filter((character) => character.status !== 'removed'); const existingRemovedHolder = state?.holderCharacterId ? characters.find((character) => character.id === state.holderCharacterId && character.status === 'removed') : undefined; return <div className="space-y-4"><p className="text-xs leading-5 text-[#969b9a]">An object can be held by a character or placed at a location, never both. Choosing one clears the other.</p><Message state={formState} /><form action={action} className="space-y-4"><div><label htmlFor={`holder-${object.id}`} className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">Held by</label><select id={`holder-${object.id}`} name="holderCharacterId" value={holder} onChange={(event) => { setHolder(event.target.value); if (event.target.value) setLocation(''); }} className={inputClass(Boolean(formState.errors.holderCharacterId))}><option value="">Unknown / not initialized</option>{existingRemovedHolder && <option value={existingRemovedHolder.id}>{existingRemovedHolder.name} — current holder (removed)</option>}{available.map((character) => <option key={character.id} value={character.id}>{character.name}</option>)}</select><ErrorText text={formState.errors.holderCharacterId} /></div><div><label htmlFor={`object-location-${object.id}`} className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">At location</label><select id={`object-location-${object.id}`} name="locationId" value={location} onChange={(event) => { setLocation(event.target.value); if (event.target.value) setHolder(''); }} className={inputClass(Boolean(formState.errors.locationId))}><option value="">Unknown / not initialized</option>{locations.map((place) => <option key={place.id} value={place.id}>{place.name}</option>)}</select><ErrorText text={formState.errors.locationId} /></div><Field label="Condition" name="condition" value={value('condition')} error={formState.errors.condition} optional placeholder="Leave blank if unknown" /><div className="flex justify-end"><Submit pending={pending} label="Save object state" /></div></form>{state && <MutationForm action={clearObjectStateAction.bind(null, projectId, object.id)} label="Clear object state" />}</div>; }
