'use client';

import { useActionState } from 'react';
import type { WorldRule } from '@/domain/world';
import type { Character, CharacterStatus } from '@/domain/character';
import type { CharacterRelationship } from '@/domain/relationship';
import type { Location } from '@/domain/location';
import {
  createWorldRuleAction, updateWorldRuleAction, deleteWorldRuleAction, toggleWorldRuleAction,
  createCharacterAction, updateCharacterAction, setCharacterStatusAction, removeCharacterAction,
  createRelationshipAction, updateRelationshipAction, deleteRelationshipAction,
  createLocationAction, updateLocationAction, deleteLocationAction, type BibleFormState, type MutationState,
} from '@/app/actions/storyBible';

const empty: BibleFormState = { errors: {}, values: {} };
const inputClass = (error = false) => `w-full border bg-[#151918] px-3 py-3 text-sm text-[#e8e8e3] outline-none placeholder:text-[#606765] focus:border-[#c5e86c] ${error ? 'border-[#f09a8b]' : 'border-[#2b3030]'}`;
const ErrorText = ({ text }: { text?: string }) => text ? <p className="mt-2 text-xs text-[#f09a8b]">{text}</p> : null;
const Message = ({ state }: { state: BibleFormState }) => state.message ? <div role="alert" className="border border-[#805047] bg-[#2b1b19] px-4 py-3 text-sm text-[#f09a8b]">{state.message}</div> : null;
function Field({ label, name, value, error, required = true, area = false, placeholder }: { label: string; name: string; value: string; error?: string; required?: boolean; area?: boolean; placeholder?: string }) { return <div><label htmlFor={name} className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">{label} {required && <span className="text-[#c5e86c]">*</span>}</label>{area ? <textarea id={name} name={name} defaultValue={value} required={required} rows={4} placeholder={placeholder} className={inputClass(Boolean(error))} /> : <input id={name} name={name} defaultValue={value} required={required} placeholder={placeholder} className={inputClass(Boolean(error))} />}<ErrorText text={error} /></div>; }
function Submit({ pending, label }: { pending: boolean; label: string }) { return <button disabled={pending} className="bg-[#c5e86c] px-5 py-3 text-sm font-bold text-[#0d1110] hover:bg-[#d8f48e] disabled:opacity-60">{pending ? 'Saving…' : label}</button>; }
type MutationAction = (previous: MutationState, data: FormData) => Promise<MutationState>;
function MutationForm({ action, label, danger = false }: { action: MutationAction; label: string; danger?: boolean }) { const [state, formAction, pending] = useActionState(action, {}); return <form action={formAction}><button disabled={pending} className={`text-xs hover:text-white disabled:opacity-60 ${danger ? 'text-[#f09a8b]' : 'text-[#969b9a]'}`}>{pending ? 'Working…' : label}</button>{state.error && <p role="alert" className="mt-2 max-w-xs text-xs leading-5 text-[#f09a8b]">{state.error}</p>}</form>; }
function InlineDelete({ action, label }: { action: MutationAction; label: string }) { return <MutationForm action={action} label={label} danger />; }

export function WorldRuleForm({ projectId, rule }: { projectId: string; rule?: WorldRule }) {
  const initial: BibleFormState = { errors: {}, values: { rule: rule?.rule ?? '' } };
  const formAction = rule ? updateWorldRuleAction.bind(null, projectId, rule.id) : createWorldRuleAction.bind(null, projectId);
  const [state, action, pending] = useActionState(formAction, initial);
  return <form action={action} className="space-y-5"><Message state={state} /><Field label="Rule" name="rule" value={state.values.rule ?? ''} error={state.errors.rule} area placeholder="One clear rule that protects continuity." />{!rule && <label className="flex items-center gap-2 text-sm text-[#969b9a]"><input type="checkbox" name="locked" className="accent-[#c5e86c]" /> Lock as canon immediately</label>}<div className="flex justify-end"><Submit pending={pending} label={rule ? 'Save rule' : 'Add rule'} /></div></form>;
}

export function WorldRuleActions({ projectId, rule }: { projectId: string; rule: WorldRule }) { return <div className="flex flex-wrap items-center gap-4">{rule.locked ? <><span className="mono text-[10px] uppercase tracking-[.14em] text-[#c5e86c]">Locked canon</span><MutationForm action={toggleWorldRuleAction.bind(null, projectId, rule.id, rule.locked)} label="Unlock to edit" /></> : <><details><summary className="cursor-pointer text-xs text-[#969b9a] hover:text-white">Edit</summary><div className="absolute right-0 z-10 mt-2 w-[min(28rem,calc(100vw-3rem))] border border-[#2b3030] bg-[#151918] p-4"><WorldRuleForm projectId={projectId} rule={rule} /></div></details><MutationForm action={toggleWorldRuleAction.bind(null, projectId, rule.id, rule.locked)} label="Lock" /><InlineDelete action={deleteWorldRuleAction.bind(null, projectId, rule.id)} label="Delete" /></>}</div>; }

function characterValues(character?: Character): Record<string, string> { return { name: character?.name ?? '', role: character?.role ?? '', visualDescription: character?.visualDescription ?? '', personality: character?.personality.join('\n') ?? '', voiceStyle: character?.voiceStyle ?? '', lockedTraits: character?.lockedTraits.join('\n') ?? '' }; }
export function CharacterForm({ projectId, character }: { projectId: string; character?: Character }) { const initial: BibleFormState = { errors: {}, values: characterValues(character) }; const formAction = character ? updateCharacterAction.bind(null, projectId, character.id) : createCharacterAction.bind(null, projectId); const [state, action, pending] = useActionState(formAction, initial); const v = (key: string) => state.values[key] ?? ''; return <form action={action} className="space-y-6"><Message state={state} /><div className="grid gap-6 md:grid-cols-2"><Field label="Name" name="name" value={v('name')} error={state.errors.name} placeholder="Character name" /><Field label="Role" name="role" value={v('role')} error={state.errors.role} placeholder="Their role in the story" /><Field label="Visual description" name="visualDescription" value={v('visualDescription')} error={state.errors.visualDescription} area placeholder="The details that should stay consistent." /><Field label="Voice style" name="voiceStyle" value={v('voiceStyle')} error={state.errors.voiceStyle} placeholder="How they speak" /></div><div className="grid gap-6 md:grid-cols-2"><Field label="Personality" name="personality" value={v('personality')} error={state.errors.personality} area placeholder="One trait per line" /><Field label="Locked traits" name="lockedTraits" value={v('lockedTraits')} error={state.errors.lockedTraits} area placeholder="One canon trait per line" /></div><div className="flex justify-end border-t border-[#2b3030] pt-6"><Submit pending={pending} label={character ? 'Save character' : 'Add character'} /></div></form>; }
export function CharacterStatusActions({ projectId, character }: { projectId: string; character: Character }) { const statuses: CharacterStatus[] = ['active', 'inactive', 'missing']; return <div className="flex flex-wrap items-start gap-4"><div className="flex flex-wrap gap-4">{character.status !== 'removed' && statuses.map((status) => <MutationForm key={status} action={setCharacterStatusAction.bind(null, projectId, character.id, status)} label={character.status === status ? `Current: ${status}` : `Set ${status}`} />)}</div>{character.status !== 'removed' && <MutationForm action={removeCharacterAction.bind(null, projectId, character.id)} label="Remove character (soft)" danger />}</div>; }

function relationshipValues(item?: CharacterRelationship): Record<string, string> { return { fromCharacterId: item?.fromCharacterId ?? '', toCharacterId: item?.toCharacterId ?? '', type: item?.type ?? '', description: item?.description ?? '', strength: item?.strength == null ? '' : String(item.strength) }; }
export function RelationshipForm({ projectId, characters, relationship }: { projectId: string; characters: Character[]; relationship?: CharacterRelationship }) { const initial: BibleFormState = { errors: {}, values: relationshipValues(relationship) }; const formAction = relationship ? updateRelationshipAction.bind(null, projectId, relationship.id) : createRelationshipAction.bind(null, projectId); const [state, action, pending] = useActionState(formAction, initial); const v = (key: string) => state.values[key] ?? ''; const available = characters.filter((character) => character.status !== 'removed'); return <form action={action} className="space-y-5"><Message state={state} />{!relationship && <div className="grid gap-5 md:grid-cols-2"><div><label htmlFor="fromCharacterId" className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">From <span className="text-[#c5e86c]">*</span></label><select id="fromCharacterId" name="fromCharacterId" required defaultValue={v('fromCharacterId')} className={inputClass(Boolean(state.errors.fromCharacterId))}><option value="">Select character</option>{available.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><ErrorText text={state.errors.fromCharacterId} /></div><div><label htmlFor="toCharacterId" className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#969b9a]">To <span className="text-[#c5e86c]">*</span></label><select id="toCharacterId" name="toCharacterId" required defaultValue={v('toCharacterId')} className={inputClass(Boolean(state.errors.toCharacterId))}><option value="">Select character</option>{available.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><ErrorText text={state.errors.toCharacterId} /></div></div>}<Field label="Relationship type" name="type" value={v('type')} error={state.errors.type} placeholder="e.g. sibling, rival" /><Field label="Description" name="description" value={v('description')} error={state.errors.description} area placeholder="Describe this directional relationship." /><Field label="Strength (optional, 0–100)" name="strength" value={v('strength')} error={state.errors.strength} required={false} placeholder="Leave blank if unknown" /><div className="flex justify-end"><Submit pending={pending} label={relationship ? 'Save relationship' : 'Add relationship'} /></div></form>; }
export function RelationshipDelete({ projectId, relationshipId }: { projectId: string; relationshipId: string }) { return <InlineDelete action={deleteRelationshipAction.bind(null, projectId, relationshipId)} label="Delete relationship" />; }

function locationValues(location?: Location): Record<string, string> { return { name: location?.name ?? '', description: location?.description ?? '', visualLock: location?.visualLock ?? '' }; }
export function LocationForm({ projectId, location }: { projectId: string; location?: Location }) { const initial: BibleFormState = { errors: {}, values: locationValues(location) }; const formAction = location ? updateLocationAction.bind(null, projectId, location.id) : createLocationAction.bind(null, projectId); const [state, action, pending] = useActionState(formAction, initial); const v = (key: string) => state.values[key] ?? ''; return <form action={action} className="space-y-5"><Message state={state} /><Field label="Location name" name="name" value={v('name')} error={state.errors.name} placeholder="e.g. Apartment kitchen" /><Field label="Description" name="description" value={v('description')} error={state.errors.description} area placeholder="What should remain visually consistent?" /><Field label="Visual lock (optional)" name="visualLock" value={v('visualLock')} error={state.errors.visualLock} required={false} area placeholder="A concise locked visual reference" /><div className="flex justify-end"><Submit pending={pending} label={location ? 'Save location' : 'Add location'} /></div></form>; }
export function LocationDelete({ projectId, locationId }: { projectId: string; locationId: string }) { return <InlineDelete action={deleteLocationAction.bind(null, projectId, locationId)} label="Delete location" />; }
