import { notFound } from 'next/navigation';
import { getProject } from '@/domain/project';
import { listCharacters } from '@/domain/character';
import { listRelationshipsByProject } from '@/domain/relationship';
import { RelationshipDelete, RelationshipForm } from '@/components/StoryBibleForms';
import { StoryBibleHeader, StoryBibleEmpty } from '@/components/StoryBibleLayout';

export const dynamic = 'force-dynamic';
export default async function RelationshipsPage({ params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const project = await getProject(projectId); if (!project) notFound(); const [characters, relationships] = await Promise.all([listCharacters(projectId), listRelationshipsByProject(projectId)]); const names = new Map(characters.map((character) => [character.id, character.name])); return <main className="mx-auto max-w-5xl px-5 py-10 lg:px-8 lg:py-14"><StoryBibleHeader projectId={projectId} title="Relationships" eyebrow="Story bible / connections" copy="Directional relationships with enough context to keep character dynamics clear." active="relationships" /><div className="grid gap-10 lg:grid-cols-[1fr_300px]"><section><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Connections</h2><span className="mono text-[10px] uppercase tracking-[.16em] text-[#707776]">{relationships.length} relationships</span></div>{relationships.length === 0 ? <StoryBibleEmpty text="No relationships yet. Add a directional connection between two characters." /> : <div className="space-y-3">{relationships.map((item) => <article key={item.id} className="border border-[#2b3030] bg-[#151918] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold">{names.get(item.fromCharacterId) ?? 'Unknown'} <span className="px-2 text-[#c5e86c]">→</span> {names.get(item.toCharacterId) ?? 'Unknown'}</p><p className="mt-2 text-xs uppercase tracking-[.12em] text-[#969b9a]">{item.type}{item.strength !== null ? ` · strength ${item.strength}` : ''}</p></div><RelationshipDelete projectId={projectId} relationshipId={item.id} /></div><p className="mt-4 text-sm leading-6 text-[#969b9a]">{item.description}</p><details className="mt-4"><summary className="cursor-pointer text-xs text-[#969b9a] hover:text-white">Edit relationship</summary><div className="mt-4"><RelationshipForm projectId={projectId} characters={characters} relationship={item} /></div></details></article>)}</div>}</section><aside className="h-fit border border-[#2b3030] bg-[#151918] p-5"><p className="mono mb-5 text-[10px] uppercase tracking-[.16em] text-[#c5e86c]">Add relationship</p>{characters.filter((character) => character.status !== 'removed').length < 2 ? <p className="text-sm leading-6 text-[#969b9a]">Keep at least two active characters in the roster before adding a relationship.</p> : <RelationshipForm projectId={projectId} characters={characters} />}</aside></div></main>; }
