import { notFound } from 'next/navigation';
import { getProject } from '@/domain/project';
import { listCharacters } from '@/domain/character';
import { listLocations } from '@/domain/location';
import { listStoryObjects } from '@/domain/object';
import { listCharacterStates, listObjectStates } from '@/domain/state';
import { CharacterStateForm, ObjectStateForm } from '@/components/CurrentStateForms';
import { StoryBibleEmpty, StoryBibleHeader } from '@/components/StoryBibleLayout';

export const dynamic = 'force-dynamic';
export default async function StatePage({ params }: { params: Promise<{ projectId: string }> }) { const { projectId } = await params; const project = await getProject(projectId); if (!project) notFound(); const [characters, objects, locations, characterStates, objectStates] = await Promise.all([listCharacters(projectId), listStoryObjects(projectId), listLocations(projectId), listCharacterStates(projectId), listObjectStates(projectId)]); const characterStateMap = new Map(characterStates.map((state) => [state.characterId, state])); const objectStateMap = new Map(objectStates.map((state) => [state.objectId, state])); return <main className="mx-auto max-w-5xl px-5 py-10 lg:px-8 lg:py-14"><StoryBibleHeader projectId={projectId} title="Current state" eyebrow="Current story / state" copy="The present state of every character and object. Unknown means no state has been initialized." active="state" /><div className="space-y-12"><section><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Characters</h2><span className="mono text-[10px] uppercase tracking-[.16em] text-[#707776]">{characters.length} characters</span></div>{characters.length === 0 ? <StoryBibleEmpty text="No characters to track yet." /> : <div className="grid gap-3 lg:grid-cols-2">{characters.map((character) => <article key={character.id} className={`border p-5 ${character.status === 'removed' ? 'border-[#49312e] bg-[#1b1817]' : 'border-[#2b3030] bg-[#151918]'}`}><div className="mb-5 flex items-start justify-between gap-3"><div><h3 className="font-semibold">{character.name}</h3><p className="mt-1 text-xs text-[#969b9a]">{character.role}</p></div><span className="mono text-[10px] uppercase tracking-[.14em] text-[#c5e86c]">{characterStateMap.has(character.id) ? character.status : 'Unknown'}</span></div><CharacterStateForm projectId={projectId} character={character} state={characterStateMap.get(character.id)} locations={locations} /></article>)}</div>}</section><section><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Objects</h2><span className="mono text-[10px] uppercase tracking-[.16em] text-[#707776]">{objects.length} objects</span></div>{objects.length === 0 ? <StoryBibleEmpty text="No objects to track yet." /> : <div className="grid gap-3 lg:grid-cols-2">{objects.map((object) => <article key={object.id} className="border border-[#2b3030] bg-[#151918] p-5"><div className="mb-5 flex items-start justify-between gap-3"><h3 className="font-semibold">{object.name}</h3><span className="mono text-[10px] uppercase tracking-[.14em] text-[#c5e86c]">{objectStateMap.has(object.id) ? 'Initialized' : 'Unknown'}</span></div><ObjectStateForm projectId={projectId} object={object} state={objectStateMap.get(object.id)} characters={characters} locations={locations} /></article>)}</div>}</section></div></main>; }
