import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getProject } from '@/domain/project';
import { getCharacter } from '@/domain/character';
import { listRelationshipsInvolvingCharacter } from '@/domain/relationship';
import { CharacterForm, CharacterStatusActions } from '@/components/StoryBibleForms';
import { WorkspaceNav } from '@/components/WorkspaceNav';

export const dynamic = 'force-dynamic';
export default async function CharacterPage({ params }: { params: Promise<{ projectId: string; characterId: string }> }) { const { projectId, characterId } = await params; const project = await getProject(projectId); const character = await getCharacter(projectId, characterId); if (!project || !character) notFound(); const relationships = await listRelationshipsInvolvingCharacter(projectId, characterId); return <main className="mx-auto max-w-5xl px-5 py-10 lg:px-8 lg:py-14"><Link href={`/projects/${projectId}/characters`} className="mono text-[10px] uppercase tracking-[.18em] text-[#969b9a] hover:text-[#c5e86c]">← Characters</Link><div className="mt-8 flex flex-wrap items-start justify-between gap-5"><div><p className="mono mb-3 text-[10px] uppercase tracking-[.22em] text-[#c5e86c]">Character dossier</p><h1 className="text-4xl font-semibold tracking-[-.04em]">{character.name}</h1><p className="mt-2 text-sm text-[#969b9a]">{character.role} · {character.status}</p></div><CharacterStatusActions projectId={projectId} character={character} /></div><div className="mt-8"><WorkspaceNav projectId={projectId} active="characters" /></div><div className="grid gap-10 lg:grid-cols-[1fr_280px]"><section><h2 className="mb-6 text-lg font-semibold">Identity and traits</h2><CharacterForm projectId={projectId} character={character} /></section><aside className="h-fit border border-[#2b3030] bg-[#151918] p-5"><p className="mono text-[10px] uppercase tracking-[.16em] text-[#c5e86c]">Relationships</p>{relationships.length === 0 ? <p className="mt-4 text-sm leading-6 text-[#969b9a]">No relationships recorded.</p> : <ul className="mt-4 space-y-3">{relationships.map((item) => <li key={item.id} className="border-b border-[#2b3030] pb-3 text-sm"><p className="font-semibold">{item.type}</p><p className="mt-1 text-xs leading-5 text-[#969b9a]">{item.description}</p></li>)}</ul>}<Link href={`/projects/${projectId}/relationships`} className="mt-5 inline-block text-xs text-[#c5e86c] hover:text-white">Manage relationships →</Link></aside></div></main>; }
