'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createWorldRule, deleteWorldRule, setWorldRuleLocked, updateWorldRule, type WorldRuleInput } from '@/domain/world';
import { createCharacter, deleteCharacter, setCharacterStatus, updateCharacter, type CharacterInput, type CharacterStatus } from '@/domain/character';
import { createRelationship, deleteRelationship, updateRelationship, type CharacterRelationshipInput } from '@/domain/relationship';
import { createLocation, deleteLocation, updateLocation, type LocationInput } from '@/domain/location';

export type BibleFormState = { errors: Record<string, string>; values: Record<string, string>; message?: string };
export type MutationState = { error?: string };
const empty: BibleFormState = { errors: {}, values: {} };
const mutationEmpty: MutationState = {};
const text = (data: FormData, key: string) => String(data.get(key) ?? '');
const lines = (value: string) => value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
const remember = (values: Record<string, string>, error?: unknown): BibleFormState => ({ errors: domainErrors(error), values, message: error ? errorMessage(error) : undefined });
function domainErrors(error: unknown): Record<string, string> { if (typeof error === 'object' && error !== null && 'errors' in error && typeof error.errors === 'object' && error.errors !== null) return Object.fromEntries(Object.entries(error.errors).map(([key, value]) => [key, String(value)])); return {}; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'The change could not be saved. Try again.'; }
function values(data: FormData, keys: string[]) { return Object.fromEntries(keys.map((key) => [key, text(data, key)])); }
function worldValues(data: FormData) { return values(data, ['rule']); }
function characterValues(data: FormData) { return values(data, ['name', 'role', 'visualDescription', 'personality', 'voiceStyle', 'lockedTraits']); }
function relationshipValues(data: FormData) { return values(data, ['fromCharacterId', 'toCharacterId', 'type', 'description', 'strength']); }
function locationValues(data: FormData) { return values(data, ['name', 'description', 'visualLock']); }
function refresh(projectId: string, section: string, detail?: string) { revalidatePath(`/projects/${projectId}/${section}`, 'page'); if (detail) revalidatePath(`/projects/${projectId}/${section}/${detail}`, 'page'); }

export async function createWorldRuleAction(projectId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { const input: WorldRuleInput = { rule: text(data, 'rule'), locked: data.get('locked') === 'on' }; try { await createWorldRule(projectId, input); } catch (error) { return remember(worldValues(data), error); } refresh(projectId, 'world'); redirect(`/projects/${projectId}/world`); }
export async function updateWorldRuleAction(projectId: string, ruleId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { const input = { rule: text(data, 'rule') }; try { await updateWorldRule(projectId, ruleId, input); } catch (error) { return remember(worldValues(data), error); } refresh(projectId, 'world'); redirect(`/projects/${projectId}/world`); }
export async function deleteWorldRuleAction(projectId: string, ruleId: string, _prev: MutationState = mutationEmpty, _data?: FormData): Promise<MutationState> { try { await deleteWorldRule(projectId, ruleId); } catch (error) { return { error: errorMessage(error) }; } refresh(projectId, 'world'); redirect(`/projects/${projectId}/world`); }
export async function toggleWorldRuleAction(projectId: string, ruleId: string, locked: boolean, _prev: MutationState = mutationEmpty, _data?: FormData): Promise<MutationState> { try { await setWorldRuleLocked(projectId, ruleId, !locked); } catch (error) { return { error: errorMessage(error) }; } refresh(projectId, 'world'); redirect(`/projects/${projectId}/world`); }

function characterInput(data: FormData): CharacterInput { return { name: text(data, 'name'), role: text(data, 'role'), visualDescription: text(data, 'visualDescription'), personality: lines(text(data, 'personality')), voiceStyle: text(data, 'voiceStyle'), lockedTraits: lines(text(data, 'lockedTraits')) }; }
export async function createCharacterAction(projectId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { try { await createCharacter(projectId, characterInput(data)); } catch (error) { return remember(characterValues(data), error); } refresh(projectId, 'characters'); redirect(`/projects/${projectId}/characters`); }
export async function updateCharacterAction(projectId: string, characterId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { try { await updateCharacter(projectId, characterId, characterInput(data)); } catch (error) { return remember(characterValues(data), error); } refresh(projectId, 'characters', characterId); revalidatePath(`/projects/${projectId}/characters`, 'layout'); redirect(`/projects/${projectId}/characters/${characterId}`); }
export async function setCharacterStatusAction(projectId: string, characterId: string, status: CharacterStatus, _prev: MutationState = mutationEmpty, _data?: FormData): Promise<MutationState> { try { await setCharacterStatus(projectId, characterId, status); } catch (error) { return { error: errorMessage(error) }; } refresh(projectId, 'characters', characterId); revalidatePath(`/projects/${projectId}/characters`, 'layout'); redirect(`/projects/${projectId}/characters/${characterId}`); }
export async function removeCharacterAction(projectId: string, characterId: string, _prev: MutationState = mutationEmpty, _data?: FormData): Promise<MutationState> { try { await deleteCharacter(projectId, characterId); } catch (error) { return { error: errorMessage(error) }; } refresh(projectId, 'characters', characterId); revalidatePath(`/projects/${projectId}/characters`, 'layout'); redirect(`/projects/${projectId}/characters`); }

function relationshipInput(data: FormData): CharacterRelationshipInput { const raw = text(data, 'strength'); return { fromCharacterId: text(data, 'fromCharacterId'), toCharacterId: text(data, 'toCharacterId'), type: text(data, 'type'), description: text(data, 'description'), strength: raw === '' ? null : Number(raw) }; }
export async function createRelationshipAction(projectId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { try { await createRelationship(projectId, relationshipInput(data)); } catch (error) { return remember(relationshipValues(data), error); } refresh(projectId, 'relationships'); revalidatePath(`/projects/${projectId}/characters`, 'layout'); redirect(`/projects/${projectId}/relationships`); }
export async function updateRelationshipAction(projectId: string, relationshipId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { const raw = text(data, 'strength'); try { await updateRelationship(projectId, relationshipId, { type: text(data, 'type'), description: text(data, 'description'), strength: raw === '' ? null : Number(raw) }); } catch (error) { return remember(relationshipValues(data), error); } refresh(projectId, 'relationships'); revalidatePath(`/projects/${projectId}/characters`, 'layout'); redirect(`/projects/${projectId}/relationships`); }
export async function deleteRelationshipAction(projectId: string, relationshipId: string, _prev: MutationState = mutationEmpty, _data?: FormData): Promise<MutationState> { try { await deleteRelationship(projectId, relationshipId); } catch (error) { return { error: errorMessage(error) }; } refresh(projectId, 'relationships'); revalidatePath(`/projects/${projectId}/characters`, 'layout'); redirect(`/projects/${projectId}/relationships`); }

export async function createLocationAction(projectId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { const input: LocationInput = { name: text(data, 'name'), description: text(data, 'description'), visualLock: text(data, 'visualLock') || null }; try { await createLocation(projectId, input); } catch (error) { return remember(locationValues(data), error); } refresh(projectId, 'locations'); redirect(`/projects/${projectId}/locations`); }
export async function updateLocationAction(projectId: string, locationId: string, _prev: BibleFormState = empty, data: FormData): Promise<BibleFormState> { const input: LocationInput = { name: text(data, 'name'), description: text(data, 'description'), visualLock: text(data, 'visualLock') || null }; try { await updateLocation(projectId, locationId, input); } catch (error) { return remember(locationValues(data), error); } refresh(projectId, 'locations'); redirect(`/projects/${projectId}/locations`); }
export async function deleteLocationAction(projectId: string, locationId: string, _prev: MutationState = mutationEmpty, _data?: FormData): Promise<MutationState> { try { await deleteLocation(projectId, locationId); } catch (error) { return { error: errorMessage(error) }; } refresh(projectId, 'locations'); redirect(`/projects/${projectId}/locations`); }
